# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hole digging automaton / 挖坑自动机
email: momocraft@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random code, post, app, and stuff. Mostly web-related.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jokester.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tarsylia
github_username:  jokester
google_analytics: UA-39627402-1
disqus:
  shortname: jokester-blog

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# Convert
markdown:    kramdown
highlighter: rouge
excerpt_separator: ""
kramdown:
  input: GFM
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'codehilite'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Custom collections
collections:
  posts:
    output: true
    permalink: /post/:year-:month/:title/
  pages:
    output: true
    permalink: /:title/

# default for collections
# see https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""       # everywhere
      type: "posts"  # items in _posts dir
    values:
      layout: "post" # posts.haml in "_post" dir
  -
    scope:
      path: ""       # everywhere
      type: "pages"  # all other items
    values:
      layout: "page" # page.haml
